image: bpicode/docker_golang

variables:
  FRITZCTL_VERSION: "1.4.21"

before_script:
  - pwd
  - mkdir -p ~/go/src/github.com/bpicode/fritzctl
  - cp -r . ~/go/src/github.com/bpicode/fritzctl

  - export ORIGIN

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - cd $GOPATH/src/github.com/bpicode/fritzctl
    - make clean sysinfo build

test_job:
  stage: test
  script:
    - cd $GOPATH/src/github.com/bpicode/fritzctl
    - make clean sysinfo test

cq_job:
  stage: test
  script:
    - cd $GOPATH/src/github.com/bpicode/fritzctl
    - make clean codequality

deploy_job:
  only:
    - web
    - tags
  stage: deploy
  script:
    - cd $GOPATH/src/github.com/bpicode/fritzctl
    - echo "$DEB_SIGNING_KEY_PRIVATE" | gpg --import
    - make clean sysinfo dist_all pkg_all sign_deb publish_all release_github
    - gpg --batch --delete-secret-and-public-keys --yes 0A56A1CE2DFCECA404A5C884E4598EE3D0E416CE
    - cp -r $GOPATH/src/github.com/bpicode/fritzctl/build $CI_PROJECT_DIR
  artifacts:
      name: fritzctl_v1.4.21_all
      paths:
        - ./build/distributions/fritzctl*
