name: Continuous Integration
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Environment information
      run: |
        echo "UNAME: $(uname -a)"
        echo "PWD: $(pwd)"
        echo "PATH: ${PATH}"
        echo "GO: $(go version)"
        echo "GO ENV: $(go env)"

    - name: Build
      run: go build -v

    - name: Test
      run: go test -run '(Test|Example)' -race -coverprofile=coverage.out -covermode=atomic ./...

    - name: Verify dependencies have expected content
      run: go mod verify

    - name: Code quality (revive)
      run: |
        go get -u github.com/mgechev/revive
        go run github.com/mgechev/revive -formatter friendly -exclude vendor/... ./...

    - name: Code quality (formatting)
      run: (gofmt -s -l -d -e $(find . -type f -name '*.go' -not -path "./vendor/*") | tee /dev/stderr) || exit 1;

    - name: Code quality (vet)
      run: go vet ./...

    - name: Code quality (bounded cyclomatic complexity)
      run: |
        go get -u github.com/fzipp/gocyclo
        go run github.com/fzipp/gocyclo -over 15 $(find . -type f -name '*.go' -not -path "./vendor/*")

    - name: Code quality (golint style mistakes)
      run: |
        go get -u golang.org/x/lint/golint
        go run golang.org/x/lint/golint -set_exit_status $(go list ./...)

    - name: Code quality (detect ineffectual assignments)
      run: |
        go get -u github.com/gordonklaus/ineffassign
        go run github.com/gordonklaus/ineffassign .

    - name: Code quality (spelling mistakes)
      run: |
        go get -u github.com/client9/misspell/cmd/misspell
        go run github.com/client9/misspell/cmd/misspell --error $(find . -type f -not -path "./vendor/*" -not -path "./.git/*")

    - name: Code quality (bugs, suggest code simplifications, point out dead code, and more)
      run: |
        go get -u honnef.co/go/tools/cmd/staticcheck
        go run honnef.co/go/tools/cmd/staticcheck -checks=all ./...

    - name: Code quality (identify unnecessary type conversions)
      run: |
        go get -u github.com/mdempsky/unconvert
        go run github.com/mdempsky/unconvert -v ./...

    - name: Notify Go Report Card
      run: curl -XPOST https://goreportcard.com/checks -F 'repo=github.com/bpicode/fritzctl'
